# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ab14816a57de7ce2d9eed8bbcc92b17d89f6a6f02a56d8c4a417b4d6129fc8ac94ba33cf0ec2b057be8f5a360902ea54dc8bf48e4de43e3a4c1815d16e09d0e

test:
  secret_key_base: 72fdc7ab28b78fb29122fb31d35efc0ba2310a925e8e2df5806fc3147f62994f13cb29b5ca7de403271cd948421fc123ad7a8d71e4b82bd7ccbb1fd14636aa01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
